name: Build and deploy to GH Pages

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency: 
  group: "pages" 
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload built files
        uses: actions/upload-artifact@v4
        with: 
          name: github-pages
          path: ./dist
  deploy: 
    environment:   
      name: github-pages
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
